title: 2D Grass
markdown: kramdown
kramdown:
  math-engine: katex
remote_theme: daattali/beautiful-jekyll
page-col: "#87c084"
footer-col: "#638a76"
layout: minimal
plugins:
  - jekyll-title-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
